apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-devops-app
  template:
    metadata:
      labels:
        app: java-devops-app
    spec:
      containers:
      - name: java-devops-container
        image: sirireddyyanamala/java-devops-project:v1
        ports:
        - containerPort: 8080